# This workflow will do a clean installation of node dependencies, cache/restore them, and run a script to build android icons
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Android Icons

on:
  workflow_dispatch:
    types: [ requested ]
    branches: [ main ]
  push:
    branches:
      - main

jobs:
  build-android-icons:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Build Android Icons
        run: npm run build:android
